const jwt = require("jsonwebtoken");
const JWTSecret = "$$You are not $welcome&&#";//our jwt signature(random string generated by us)

//middleware function will help us to know wheather the user is authenticated or not.
// it generally takes three arguments req,res,next  .next function will help us to execute the next fuction where
// we would use middlleware






const fetchuser = (req, res, next) => {
  //get the user from jwt token and add the user id to the req object

  const token = req.header("auth-token");//make sure to send auth token with the same name as access here. for here it is auth-token

  if (token == false)
    return res
      .status(401)
      .send({ error: "please authenticate with valid credentials" });
  try {

      const data=jwt.verify(token,JWTSecret)
      req.user=data.user


      next(); //make sure to call next()  at the end of the function

  } catch {
    res
    .status(401)
    .send({ error: "please authenticate with valid credentials" });

  }
};

module.exports = fetchuser;
